apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: paw-data-innlop
  namespace: paw
  labels:
    team: paw
spec:
  image: {{image}}
  replicas:
    min: 1
    max: 1
  kafka:
    pool: {{kafka.pool}}
  secureLogs:
    enabled: true
  env:
    - name: KAFKA_CONSUMER_GROUP_ID
      value: paw-data-innlop-group-v3
    - name: AUTOMATISK_REAKTIVERING_TOPIC
      value: paw.arbeidssoker-reaktivering-v1
    - name: DATA_REAKTIVERING_TOPIC
      value: paw.data-innlop-reaktivering-v1
    - name: DATA_REAKTIVERING_SVAR_TOPIC
      value: paw.data-innlop-reaktivering-svar-v1
    - name: PDL_CLUSTER
      value: {{pdlCluster}}
    - name: PDL_URL
      value: {{pdlUrl}}


