apiVersion: "kafka.nais.io/v1"
kind: "Topic"
metadata:
  name: {{topic}}
  namespace: paw
  labels:
    team: paw
spec:
  pool: {{kafka}}
  config:
    cleanupPolicy: delete
    minimumInSyncReplicas: 1
    partitions: 1
    replication: 3
    retentionBytes: -1
    retentionHours: 72
  acl:
    - team: paw
      application: paw-kafka-connect
      access: read
    - team: paw
      application: paw-data-innlop
      access: readwrite
    - application: maccyber
      team: paw
      access: readwrite
