name: Deploy Kafka Topics + Kafka Connectors

on:
  workflow_call:
    inputs:
      cluster:
        required: true
        type: string
      kafka:
        required: true
        type: string
      project:
        required: true
        type: string

jobs:
  deploy-topics:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        topic: [data-innlop-reaktivering-v1, data-innlop-reaktivering-svar-v1]
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: ${{ inputs.cluster }}
          RESOURCE: .nais/topic.yaml,.nais/connector.yaml
          VAR: topic=${{ matrix.topic }},kafka=${{ inputs.kafka }},project=${{ inputs.project }}
          PRINT_PAYLOAD: true
